name: Run at Midnight

on:
  schedule:
    - cron: '41 16 * * *' # Schedule the workflow to run at midnight (UTC time)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Change this to your desired Python version

    - name: Run Python script
      run: python your_script.py # Change 'your_script.py' to the name of your Python script
